BOID_VISIBILITY_RADIUS = 40
BOID_SEPARATION_RADIUS = 15
SPEED = 5
ACCELERATION_MULT = .5
SEPARATION_MULT = 3
COHESION_MULT = 0.7
ALIGNMENT_MULT = 0.8
INITIAL_BOID_SIZE = 2

CLOSE_SEPARATION_RADIUS = 3
CLOSE_SEPARATION_MULT = 10

QT_MAX_BOID = 3

KD_MAX_BOID = 5
