BOID_VISIBILITY_RADIUS = 60
BOID_SEPARATION_RADIUS = 15
SPEED = 5
ACCELERATION_MULT = .4
SEPARATION_MULT = 3
COHESION_MULT = 0.8
ALIGNMENT_MULT = 0.9
INITIAL_BOID_SIZE = 100

CLOSE_SEPARATION_RADIUS = 3
CLOSE_SEPARATION_MULT = 10

QT_MAX_BOID = 3
